AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  DiscordApplicationId:
    Type: String
  DiscordApplicationPublicKey:
    Type: String

Resources:
  AcknowledgeDiscordCommandFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/index.acknowledgeHandler
      Runtime: nodejs12.x
      Environment:
        Variables:
          APPLICATION_ID: !Ref DiscordApplicationId
          PUBLIC_KEY: !Ref DiscordApplicationPublicKey
          SQS_QUEUE_URL: !Ref ResponseQueue
      Policies:
        - SQSSendMessagePolicy:
            QueueName:
              !GetAtt ResponseQueue.QueueName
      Events:
        AcknowledgeDiscordCommand:
          Type: Api
          Properties:
            Path: /command
            Method: post
        WarmLambda:
          Type: Schedule
          Properties:
            Schedule: rate(8 minutes)
            Input: '{ "body": "warm" }'

  RespondToDiscordCommandFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/index.responseHandler
      Runtime: nodejs12.x
      Environment:
        Variables:
          APPLICATION_ID: !Ref DiscordApplicationId
          PUBLIC_KEY: !Ref DiscordApplicationPublicKey
          SQS_QUEUE_URL: !Ref ResponseQueue
      Policies:
        - SQSPollerPolicy:
            QueueName:
              !GetAtt ResponseQueue.QueueName
      Events:
        RespondToDiscordCommand:
          Type: SQS
          Properties:
            Queue: !GetAtt ResponseQueue.Arn
        WarmLambda:
          Type: Schedule
          Properties:
            Schedule: rate(8 minutes)
            Input: '{ "Records": [] }'

  ResponseQueue:
    Type: AWS::SQS::Queue

Outputs:
  HandleDiscordCommandApi:
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/command/"
